import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    "site.title": "SOMI.IM",
    "site.subtitle": "SOMI, I AM HERE!",
    "site.description": "👋 Your Premium Digital Assets",
    "site.footer": "2026 Spring Festival Promo: Contact for extra discounts!",
    "nav.contact": "Contact",
    "nav.vip": "VIP",
    "login.title": "VIP Access",
    "login.desc": "Enter passkey to access console",
    "login.placeholder": "Passkey",
    "login.enter": "Enter",
    "login.success": "Welcome back, VIP.",
    "login.denied": "Access Denied.",
    "admin.title": "SOMI Admin",
    "admin.dashboard": "Domains",
    "admin.settings": "Settings",
    "admin.logout": "Logout",
    "admin.search": "Search domains...",
    "admin.add": "Add Domain",
    "admin.edit": "Edit Domain",
    "admin.delete": "Delete",
    "admin.status": "Status",
    "admin.price": "Price",
    "admin.actions": "Actions",
    "admin.domain_name": "Domain Name",
    "status.available": "Available",
    "status.sold": "Sold",
    "status.reserved": "Reserved",
    "admin.save": "Save Changes",
    "admin.create": "Create Domain",
    "admin.expiry": "Expiry Date",
    "admin.note": "Note (Private)",
    "admin.export": "Export Data",
    "admin.backup": "Backup/Restore",
    "admin.batch_ops": "Batch Operations",
    "admin.dashboard_overview": "Overview",
    "admin.total_assets": "Total Assets",
    "admin.total_value": "Total Value",
    "admin.expiring_soon": "Expiring Soon",
    "admin.select_all": "Select All",
    "admin.selected": "{count} Selected",
    "admin.export_csv": "Export CSV",
    "admin.export_excel": "Export Excel",
    "admin.backup_download": "Download Backup",
    "admin.backup_restore": "Restore Backup",
    "toast.added": "Domain added successfully",
    "toast.updated": "Domain updated successfully",
    "toast.deleted": "Domain deleted",
    "toast.exported": "Data exported successfully",
    "toast.backup_created": "Backup created successfully",
    "toast.restored": "Data restored successfully",
    "toast.logout": "Logged out successfully",
    "lang.en": "English",
    "lang.zh": "中文",
    "admin.import": "Import Domains",
    "import.title": "Batch Import Domains",
    "import.desc": "Paste domain list or upload CSV file to add multiple domains at once.",
    "import.tab_text": "Paste Text",
    "import.tab_csv": "Upload CSV",
    "import.text_label": "Domain List",
    "import.text_placeholder": "Format: domain,price,provider,status\nExample:\nsomi.im, ¥999, Spaceship, available\nexample.com, $500, GoDaddy, sold",
    "import.csv_label": "Select CSV File",
    "import.preview": "Data Preview",
    "import.confirm": "Import {count} Domains",
    "import.success": "Successfully imported {count} domains",
    "import.error_format": "Invalid format or empty data",
    "import.col_domain": "Domain",
    "import.col_price": "Price",
    "import.col_provider": "Provider",
    "import.col_status": "Status",
    "dashboard.total_domains": "Total Domains",
    "dashboard.total_value": "Total Value",
    "dashboard.expiring_soon": "Expiring Soon",
    "dashboard.sold_domains": "Sold Domains",
    "dashboard.status_dist": "Status Distribution",
    "dashboard.suffix_share": "Extension Share",
    "dashboard.suffix_dist": "Extension Distribution",
    "dashboard.provider_dist": "Provider Distribution",
    "field.expiry": "Expiry Date",
    "field.note": "Note",
    "action.batch_delete": "Delete Selected",
    "action.batch_status": "Update Status",
    "action.selected": "{count} Selected",
    "export.excel": "Export Excel",
    "export.csv": "Export CSV",
    "backup.download": "Backup Data (JSON)",
    "backup.restore": "Restore Data",
    "backup.success": "Data restored successfully",
    "backup.error": "Invalid backup file"
  },
  zh: {
    "site.title": "SOMI.IM",
    "site.subtitle": "搜米，我在！",
    "site.description": "👋 您的臻选数字资产",
    "site.footer": "2026年春节活动，联系询价就折上折！",
    "nav.contact": "联系我们",
    "nav.vip": "VIP入口",
    "login.title": "VIP 通道",
    "login.desc": "输入访问密钥进入管理台",
    "login.placeholder": "访问密钥",
    "login.enter": "进入",
    "login.success": "欢迎回来，尊贵的会员。",
    "login.denied": "访问被拒绝。",
    "admin.title": "SOMI 管理后台",
    "admin.dashboard": "域名管理",
    "admin.settings": "系统设置",
    "admin.logout": "退出登录",
    "admin.search": "搜索域名...",
    "admin.add": "添加域名",
    "admin.edit": "编辑域名",
    "admin.delete": "删除",
    "admin.status": "状态",
    "admin.price": "价格",
    "admin.actions": "操作",
    "admin.domain_name": "域名名称",
    "status.available": "在售",
    "status.sold": "已售",
    "status.reserved": "保留",
    "admin.save": "保存修改",
    "admin.create": "创建域名",
    "admin.expiry": "到期时间",
    "admin.note": "备注 (私密)",
    "admin.export": "导出数据",
    "admin.backup": "备份/恢复",
    "admin.batch_ops": "批量操作",
    "admin.dashboard_overview": "概览",
    "admin.total_assets": "资产总数",
    "admin.total_value": "总估值",
    "admin.expiring_soon": "即将到期",
    "admin.select_all": "全选",
    "admin.selected": "已选 {count} 项",
    "admin.export_csv": "导出 CSV",
    "admin.export_excel": "导出 Excel",
    "admin.backup_download": "下载备份",
    "admin.backup_restore": "恢复备份",
    "toast.added": "域名添加成功",
    "toast.updated": "域名更新成功",
    "toast.deleted": "域名已删除",
    "toast.exported": "数据导出成功",
    "toast.backup_created": "备份创建成功",
    "toast.restored": "数据恢复成功",
    "toast.logout": "已退出登录",
    "lang.en": "English",
    "lang.zh": "中文",
    "admin.import": "批量导入",
    "import.title": "批量导入域名",
    "import.desc": "粘贴域名列表或上传 CSV 文件以批量添加数据。",
    "import.tab_text": "粘贴文本",
    "import.tab_csv": "上传 CSV",
    "import.text_label": "域名列表",
    "import.text_placeholder": "格式：域名,价格,注册商,状态\n示例：\nsomi.im, ¥999, Spaceship, available\nexample.com, $500, GoDaddy, sold",
    "import.csv_label": "选择 CSV 文件",
    "import.preview": "数据预览",
    "import.confirm": "导入 {count} 个域名",
    "import.success": "成功导入 {count} 个域名",
    "import.error_format": "格式错误或数据为空",
    "import.col_domain": "域名",
    "import.col_price": "价格",
    "import.col_provider": "注册商",
    "import.col_status": "状态",
    "dashboard.total_domains": "域名总数",
    "dashboard.total_value": "总估值",
    "dashboard.expiring_soon": "即将过期",
    "dashboard.sold_domains": "已售域名",
    "dashboard.status_dist": "状态分布",
    "dashboard.suffix_share": "后缀占比",
    "dashboard.suffix_dist": "后缀分布",
    "dashboard.provider_dist": "注册商分布",
    "field.expiry": "到期时间",
    "field.note": "备注",
    "action.batch_delete": "批量删除",
    "action.batch_status": "批量更新状态",
    "action.selected": "已选 {count} 项",
    "export.excel": "导出 Excel",
    "export.csv": "导出 CSV",
    "backup.download": "备份数据 (JSON)",
    "backup.restore": "恢复数据",
    "backup.success": "数据恢复成功",
    "backup.error": "无效的备份文件"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
